apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw13-service
spec:
  ingressClassName: nginx
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hw13-service
                port:
                  number: 80
